services:
  server: 
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8998:8998"
    networks:
      - rail_madad
    environment:
      MONGO_URL: mongodb://root:password@db:27017/
    depends_on:
      - db

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "4173:4173"
    networks:
      - rail_madad
    depends_on:
      - server

  db:
    image: mongo:4.0-xenial
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - rail_madad
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
  
networks:
  rail_madad:
    driver: bridge

volumes:
  mongo_data:
    driver: local
